### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-platform-cec:

### ISSUE THREAD

**Issue by sindudas** [jbree/homebridge-plugin-cec#3]
Installed on my working HomeBridge, but I got this error message below and can't use it. Any idea?

Jan 24 00:08:38 homebridge[3756]: [1/24/2017, 12:08:38 AM] ERROR LOADING PLUGIN homebridge-platform-cec:
Jan 24 00:08:38 homebridge[3756]: [1/24/2017, 12:08:38 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Jan 24 00:08:38 homebridge[3756]: at exports.runInThisContext (vm.js:53:16)
Jan 24 00:08:38 homebridge[3756]: at Module._compile (module.js:387:25)
Jan 24 00:08:38 homebridge[3756]: at Object.Module._extensions..js (module.js:422:10)
Jan 24 00:08:38 homebridge[3756]: at Module.load (module.js:357:32)
Jan 24 00:08:38 homebridge[3756]: at Function.Module._load (module.js:314:12)
Jan 24 00:08:38 homebridge[3756]: at Module.require (module.js:367:17)
Jan 24 00:08:38 homebridge[3756]: at require (internal/module.js:16:19)
Jan 24 00:08:38 homebridge[3756]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-cec/lib/CecPlatform.js:5:29)
Jan 24 00:08:38 homebridge[3756]: at Module._compile (module.js:413:34)
Jan 24 00:08:38 homebridge[3756]: at Object.Module._extensions..js (module.js:422:10)
Jan 24 00:08:38 homebridge[3756]: [1/24/2017, 12:08:38 AM] ====================

**Comment by jbree** [comment]
My guess is that this is a nodejs version thing. Which version are you running? I'm using 6.9.1, which may provide support for features that your version doesn't.

Perhaps I should be using babel to compile the ES6 code to something more backwards compatible.

**Comment by sindudas** [comment]
Updating to 6.9.2 it loads well.
